name = "subgraph-ts-worker-staging"
type = "javascript"
zone_id = ""
workers_dev = true
compatibility_date = "2022-01-05"
account_id = "dc83b53169c2c64bdaa6f1bdef134d7e" 

kv_namespaces = [ 
	 { id="ca8261299da44e95a5f013f662732d2e", binding = "HEALTHS", preview_id = "ca8261299da44e95a5f013f662732d2e" },
]
webpack_config = "webpack.config.js"



[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


